stage:
- Build
- Deploy

Build:
- maven:
  - mvn clean install -Dmaven.repo.local=/root/.m2/${JOB_NAME}
- docker:
  - cd docker && docker build . -t $image
  - docker images | grep cloudzcp
- docker.push:
    imageName: $image
    credentialsId: dockerhub

Deploy:
- kubectl:
  - kubectl apply -R -f $yaml
  - kubectl scale deploy zcp-portal-ui --replicas 1 -n $namespace

env:
  image: pog-dev-registry.cloudzcp.io/zcp-demo/alert:latest
  yaml: k8s

agent:
  profile: [maven, docker, kubectl]
  volumes:
  - pvc:zcp-jenkins-mvn-repo: /root/.m2
  serviceAccount: zcp-system-admin
