stage:
- Build
- Deploy

Build:
- gradle:
  - ./gradlew bootJar
- docker:
  - cd docker && docker build . -t $image
  - docker images | grep zcp-demo
- docker.push:
    imageName: $image
    credentialsId: HARBOR_CREDENTIALS

Deploy:
- kubectl:
  - kubectl apply -R -f $yaml
  - kubectl scale deploy zcp-demo --replicas 1 -n $namespace

env:
  image: pog-dev-registry.cloudzcp.io/zcp-demo/alert:latest
  yaml: k8s

agent:
  profile: [docker, kubectl]
  containers:
  - name: gradle
    image: openjdk:8-alpine
    ttyEnabled: true
    command: cat
  #volumes:
  #- pvc:zcp-jenkins-mvn-repo: /root/.m2
  serviceAccount: zcp-system-admin
