stage:
- Build
- Deploy

Build:
- gradle:
  - ./gradlew -g /cache/gradle/zcp-demo bootJar
- docker:
  - pwd
  - cd docker && docker build . -t $image
  - docker images | grep zcp-demo
- docker.push:
    imageName: $image
    credentialsId: HARBOR_CREDENTIALS

Deploy:
- kubectl:
  - kubectl apply -R -f $yaml
  - kubectl scale deploy zcp-demo --replicas 1 -n $namespace

env:
  image: pog-dev-registry.cloudzcp.io/zcp-demo/alert:latest
  yaml: k8s

agent:
  profile: [docker, kubectl]
  containers:
  - name: gradle
    image: gradle:5.3.0-jre-alpine
    ttyEnabled: true
    # command: cat
  volumes:
  - pvc:zcp-jenkins-mvn-repo: /cache
  serviceAccount: zcp-system-admin
